/**
 * Local Python bundling for the Lambda code (auth_design.md D-9).
 *
 * Docker isn't available on the dev machine, so the asset is built with a local
 * `ILocalBundling` that
 *
 * 1. installs the app's fully resolved runtime lock (`requirements-lambda.lock`, generated by
 *    the app's `scripts/lock_lambda_deps.sh` from its `pyproject.toml` pins) as Linux arm64 /
 *    CPython 3.12 wheels, hash-checked and without dependency resolution:
 *    `python3 -m pip install --platform manylinux2014_aarch64 --only-binary=:all:
 *     --python-version 3.12 --implementation cp --target <out> --no-deps --require-hashes
 *     -r <appPath>/requirements-lambda.lock`
 * 2. copies `<appPath>/src/app` to `<out>/app`.
 *
 * All functions share this single asset; each selects its handler from the contract.
 *
 * Context:
 * - `ourlore:appPath` (default `../OurloreBackendService`, relative to this repo)
 * - `ourlore:skipBundling` (`true` in tests): use a placeholder that fails if invoked.
 */
import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import { spawnSync } from 'child_process';
import { Annotations, AssetHashType, BundlingOptions, ILocalBundling } from 'aws-cdk-lib';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

export const APP_PATH_CONTEXT = 'ourlore:appPath';
export const SKIP_BUNDLING_CONTEXT = 'ourlore:skipBundling';
export const DEFAULT_APP_PATH = '../OurloreBackendService';

/** Target platform of the Lambda functions (contract runtime python3.12 / arm64). */
const PIP_PLATFORM_ARGS: readonly string[] = [
  '--platform', 'manylinux2014_aarch64',
  '--only-binary=:all:',
  '--python-version', '3.12',
  '--implementation', 'cp',
];

/** Placeholder handler used when bundling is skipped; deploying it would fail loudly. */
const PLACEHOLDER_CODE =
  'def handler(event, context):\n' +
  '    raise RuntimeError("placeholder code: synthesized with ourlore:skipBundling=true")\n';

/** App-relative path of the fully resolved, hash-pinned runtime lock (Python 3.12 / arm64). */
export const LAMBDA_LOCK_FILE = 'requirements-lambda.lock';

/** One locked requirement: `name==version` plus its `--hash` values. */
export interface LockedRequirement {
  readonly name: string;
  readonly version: string;
  readonly hashes: readonly string[];
}

/** Parsed `requirements-lambda.lock`. */
export interface LambdaLock {
  readonly path: string;
  readonly requirements: readonly LockedRequirement[];
  /** True when every entry carries a hash, so pip runs with `--require-hashes`. */
  readonly hashed: boolean;
}

/**
 * Parse and validate the app's Lambda lock (generated by `scripts/lock_lambda_deps.sh`).
 *
 * Every entry must be an exact `name==version` pin (the lock is installed with `--no-deps`,
 * so it has to be fully resolved). Hashes are all-or-nothing: a partially hashed lock is
 * rejected because pip's `--require-hashes` would fail on it anyway.
 */
export function readLambdaLock(lockPath: string): LambdaLock {
  if (!fs.existsSync(lockPath)) {
    throw new Error(`${lockPath} not found. Run scripts/lock_lambda_deps.sh in the app repo.`);
  }
  const text = fs.readFileSync(lockPath, 'utf8').replace(/\\\r?\n/g, ' ');
  const requirements: LockedRequirement[] = [];
  const seen = new Set<string>();
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.replace(/(^|\s)#.*$/, '').trim();
    if (line.length === 0) continue;
    const [requirement, ...options] = line.split(/\s+/);
    const m = /^([A-Za-z0-9._-]+)==([A-Za-z0-9.+!_-]+)$/.exec(requirement);
    if (!m) throw new Error(`${lockPath}: '${requirement}' is not an exact pin (name==version).`);
    const name = m[1].toLowerCase().replace(/[-_.]+/g, '-');
    if (seen.has(name)) throw new Error(`${lockPath}: '${name}' is locked twice.`);
    seen.add(name);
    const hashes = options.map((o) => {
      const h = /^--hash=(sha256:[0-9a-f]{64})$/.exec(o);
      if (!h) throw new Error(`${lockPath}: unsupported option '${o}' for '${name}' (only --hash=sha256:...).`);
      return h[1];
    });
    requirements.push({ name, version: m[2], hashes });
  }
  if (requirements.length === 0) throw new Error(`${lockPath}: no requirements.`);
  const hashedCount = requirements.filter((r) => r.hashes.length > 0).length;
  if (hashedCount !== 0 && hashedCount !== requirements.length) {
    throw new Error(`${lockPath}: either every entry or none must have a --hash.`);
  }
  return { path: lockPath, requirements, hashed: hashedCount === requirements.length };
}

/**
 * Arguments (after the interpreter) of the pip command that installs the lock into
 * `outputDir`. Pure, so tests can check it without running pip.
 */
export function pipInstallArgs(lock: LambdaLock, outputDir: string): string[] {
  return [
    '-m', 'pip', 'install',
    ...PIP_PLATFORM_ARGS,
    '--target', outputDir,
    '--no-deps', // the lock is fully resolved; never let pip pull anything else
    ...(lock.hashed ? ['--require-hashes'] : []),
    '--no-compile',
    '--disable-pip-version-check',
    '--no-warn-conflicts', // the host environment's packages are irrelevant to --target
    '--quiet',
    '-r', lock.path,
  ];
}

/** Recursively list files under `dir` (sorted, relative), skipping caches. */
function listSourceFiles(dir: string, rel = ''): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(path.join(dir, rel), { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    if (entry.name === '__pycache__' || entry.name.endsWith('.pyc') || entry.name === '.DS_Store') continue;
    const r = path.join(rel, entry.name);
    if (entry.isDirectory()) out.push(...listSourceFiles(dir, r));
    else if (entry.isFile()) out.push(r);
  }
  return out;
}

/**
 * Deterministic hash of the asset inputs: app sources, the lock contents, and the pip command
 * shape. CDK reuses a previously built asset with the same hash.
 */
function assetHash(appDir: string, lock: LambdaLock): string {
  const h = crypto.createHash('sha256');
  h.update(JSON.stringify({ lock: lock.requirements, args: pipInstallArgs({ ...lock, path: '<lock>' }, '<out>') }));
  for (const f of listSourceFiles(appDir)) {
    h.update(f);
    h.update('\0');
    h.update(fs.readFileSync(path.join(appDir, f)));
    h.update('\0');
  }
  return h.digest('hex');
}

/** `ILocalBundling` that runs pip locally and copies the app package. */
class LocalPythonBundling implements ILocalBundling {
  constructor(
    private readonly appDir: string,
    private readonly lock: LambdaLock,
    private readonly python: string,
  ) {}

  /** Build the asset into `outputDir`. Throws (rather than falling back to Docker) on failure. */
  tryBundle(outputDir: string, _options: BundlingOptions): boolean {
    const args = pipInstallArgs(this.lock, outputDir);
    const result = spawnSync(this.python, args, { stdio: ['ignore', 'inherit', 'inherit'] });
    if (result.error || result.status !== 0) {
      throw new Error(
        `Local bundling failed: '${this.python} ${args.join(' ')}' ` +
          `exited with ${result.status ?? 'error'}${result.error ? `: ${result.error.message}` : ''}.`,
      );
    }
    fs.cpSync(this.appDir, path.join(outputDir, 'app'), {
      recursive: true,
      filter: (src) => {
        const base = path.basename(src);
        return base !== '__pycache__' && !base.endsWith('.pyc') && base !== '.DS_Store';
      },
    });
    return true;
  }
}

/**
 * Build the single code asset shared by every function.
 *
 * @param scope any construct in the app (reads context; adds a warning when skipping)
 */
export function sharedLambdaCode(scope: Construct): lambda.Code {
  const skip = scope.node.tryGetContext(SKIP_BUNDLING_CONTEXT);
  if (skip === true || skip === 'true') {
    Annotations.of(scope).addWarningV2(
      'ourlore:placeholderCode',
      'ourlore:skipBundling is set: functions use placeholder code. Do not deploy this synth.',
    );
    return lambda.Code.fromInline(PLACEHOLDER_CODE);
  }
  const appPath = path.resolve(
    __dirname,
    '..',
    (scope.node.tryGetContext(APP_PATH_CONTEXT) as string | undefined) ?? DEFAULT_APP_PATH,
  );
  const srcDir = path.join(appPath, 'src');
  const appDir = path.join(srcDir, 'app');
  if (!fs.existsSync(appDir)) {
    throw new Error(`App sources not found at ${appDir}. Set -c ${APP_PATH_CONTEXT}=<path to OurloreBackendService>.`);
  }
  const lock = readLambdaLock(path.join(appPath, LAMBDA_LOCK_FILE));
  return lambda.Code.fromAsset(appDir, {
    assetHashType: AssetHashType.CUSTOM,
    assetHash: assetHash(appDir, lock),
    bundling: {
      // Only used if local bundling declines, which it never does (it throws instead).
      image: lambda.Runtime.PYTHON_3_12.bundlingImage,
      local: new LocalPythonBundling(appDir, lock, process.env.OURLORE_PYTHON ?? 'python3'),
    },
  });
}
