/**
 * Typed loader and validator for `contract.json` (contract version 4).
 *
 * The contract is generated by the app repo (`OurloreBackendService/src/app/contract.py`,
 * whose module docstring documents the shape) and vendored here by `./sync-contract.sh`.
 * Everything the CDK derives from it — routes, authorizers, per-function env, runtime, and
 * IAM — is validated first so a malformed or drifted contract fails synth instead of
 * producing a subtly wrong stack.
 */
import * as fs from 'fs';
import * as path from 'path';

export const SUPPORTED_CONTRACT_VERSION = 4;

export const HTTP_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] as const;
export type HttpMethodName = (typeof HTTP_METHODS)[number];

export const TABLE_ACCESS = ['read', 'read_write'] as const;
export const BUCKET_ACCESS = ['read', 'put', 'read_write', 'read_write_delete'] as const;
export const QUEUE_ACCESS = ['send', 'receive_delete'] as const;
export const SECRET_ACCESS = ['read'] as const;
export const PARAMETER_ACCESS = ['read'] as const;

export type TableAccess = (typeof TABLE_ACCESS)[number];
export type BucketAccess = (typeof BUCKET_ACCESS)[number];
export type QueueAccess = (typeof QUEUE_ACCESS)[number];
export type SecretAccess = (typeof SECRET_ACCESS)[number];
export type ParameterAccess = (typeof PARAMETER_ACCESS)[number];

/** Runtime defaults. */
export interface RuntimeSpec {
  readonly runtime: string;
  readonly architecture: string;
  readonly memory_mb: number;
  readonly timeout_seconds: number;
}

/** A table catalog entry: physical name is `ourlore-<stage>-<entity>`. */
export interface TableCatalogEntry {
  readonly env_var: string;
  readonly entity: string;
}

/** A bucket, queue, secret, or parameter catalog entry. */
export interface CatalogEntry {
  readonly env_var: string;
  readonly description: string;
}

/**
 * A bucket catalog entry (v4). Every object key starts with one of `key_prefixes` (owner-first
 * keys, D-10), so object grants and `s3:ListBucket` are scoped to them.
 */
export interface BucketCatalogEntry extends CatalogEntry {
  readonly key_prefixes: readonly string[];
}

/** What every function (group, trigger, worker) declares. */
export interface FunctionSpec {
  readonly handler: string;
  readonly env: readonly string[];
  readonly memory_mb: number;
  readonly timeout_seconds: number;
  readonly tables: Readonly<Record<string, TableAccess>>;
  readonly buckets: Readonly<Record<string, BucketAccess>>;
  readonly queues: Readonly<Record<string, QueueAccess>>;
  readonly secrets: Readonly<Record<string, SecretAccess>>;
  /** SSM parameters (operator-created `SecureString`s) the function reads by name. */
  readonly parameters: Readonly<Record<string, ParameterAccess>>;
  /** `cognito-idp` actions without the prefix; always scoped to this stage's pool. */
  readonly cognito_actions: readonly string[];
}

/** One HTTP route. */
export interface RouteSpec {
  readonly method: HttpMethodName;
  readonly path: string;
  readonly auth: boolean;
  readonly scopes: readonly string[];
}

export interface GroupSpec extends FunctionSpec {
  readonly routes: readonly RouteSpec[];
}

export type EventSourceSpec =
  | {
      readonly type: 'sqs';
      readonly queue: string;
      readonly batch_size: number;
      readonly report_batch_item_failures: boolean;
    }
  | { readonly type: 'schedule'; readonly expression: string };

export interface WorkerSpec extends FunctionSpec {
  readonly event_source: EventSourceSpec;
}

/** The whole contract. */
export interface Contract {
  readonly version: number;
  readonly runtime: RuntimeSpec;
  readonly env_vars: Readonly<Record<string, string>>;
  readonly optional_env_vars: readonly string[];
  readonly deferred_env_vars: readonly string[];
  readonly tables: Readonly<Record<string, TableCatalogEntry>>;
  readonly buckets: Readonly<Record<string, BucketCatalogEntry>>;
  readonly queues: Readonly<Record<string, CatalogEntry>>;
  readonly secrets: Readonly<Record<string, CatalogEntry>>;
  readonly parameters: Readonly<Record<string, CatalogEntry>>;
  readonly resource_groups: Readonly<Record<string, GroupSpec>>;
  readonly cognito_triggers: Readonly<Record<string, FunctionSpec>>;
  readonly workers: Readonly<Record<string, WorkerSpec>>;
}

/** Default location: the vendored copy at the repo root. */
export const DEFAULT_CONTRACT_PATH = path.join(__dirname, '..', 'contract.json');

/** Raised for any contract problem; the message names the offending key. */
export class ContractError extends Error {
  constructor(message: string) {
    super(`contract.json: ${message}`);
    this.name = 'ContractError';
  }
}

/** Read and validate a contract file. */
export function loadContract(file: string = DEFAULT_CONTRACT_PATH): Contract {
  let raw: unknown;
  try {
    raw = JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch (e) {
    throw new ContractError(`cannot read ${file}: ${(e as Error).message}`);
  }
  return parseContract(raw);
}

/** Validate an already-parsed contract object and return it typed. */
export function parseContract(raw: unknown): Contract {
  const c = raw as Contract;
  if (!isObject(raw)) throw new ContractError('top level must be an object.');
  if (c.version !== SUPPORTED_CONTRACT_VERSION) {
    throw new ContractError(`version ${String(c.version)} is not supported (expected ${SUPPORTED_CONTRACT_VERSION}).`);
  }
  for (const key of [
    'runtime', 'env_vars', 'tables', 'buckets', 'queues', 'secrets', 'parameters',
    'resource_groups', 'cognito_triggers', 'workers',
  ] as const) {
    if (!isObject(c[key])) throw new ContractError(`'${key}' must be an object.`);
  }
  for (const key of ['optional_env_vars', 'deferred_env_vars'] as const) {
    if (!Array.isArray(c[key])) throw new ContractError(`'${key}' must be a list.`);
  }

  const catalog = new Set(Object.keys(c.env_vars));
  for (const name of [...c.optional_env_vars, ...c.deferred_env_vars]) {
    if (!catalog.has(name)) throw new ContractError(`'${name}' (optional/deferred) is not in env_vars.`);
  }
  for (const [kind, entries] of [
    ['tables', c.tables], ['buckets', c.buckets], ['queues', c.queues], ['secrets', c.secrets],
    ['parameters', c.parameters],
  ] as const) {
    for (const [logical, entry] of Object.entries(entries)) {
      if (!catalog.has(entry.env_var)) {
        throw new ContractError(`${kind}.${logical}.env_var '${entry.env_var}' is not in env_vars.`);
      }
    }
  }
  for (const [logical, b] of Object.entries(c.buckets)) {
    const prefixes = (b as { key_prefixes?: unknown }).key_prefixes;
    if (!Array.isArray(prefixes) || prefixes.length === 0) {
      throw new ContractError(`buckets.${logical}.key_prefixes must be a non-empty list.`);
    }
    for (const p of prefixes) {
      if (typeof p !== 'string' || !/^[a-z0-9][a-z0-9_-]*\/$/.test(p)) {
        throw new ContractError(`buckets.${logical}.key_prefixes '${String(p)}' is invalid (expected '<name>/').`);
      }
    }
    if (new Set(prefixes).size !== prefixes.length) {
      throw new ContractError(`buckets.${logical}.key_prefixes has duplicates.`);
    }
  }
  for (const [logical, t] of Object.entries(c.tables)) {
    if (!/^[A-Z][A-Za-z]+$/.test(t.entity)) throw new ContractError(`tables.${logical}.entity '${t.entity}' is invalid.`);
  }
  // Parameters are always operator-created and always bound; the stack has no "disabled" form.
  for (const [logical, p] of Object.entries(c.parameters)) {
    if (c.optional_env_vars.includes(p.env_var) || c.deferred_env_vars.includes(p.env_var)) {
      throw new ContractError(`parameters.${logical}.env_var '${p.env_var}' must not be optional or deferred.`);
    }
  }

  const seenRoutes = new Set<string>();
  for (const [name, g] of Object.entries(c.resource_groups)) {
    validateFunction(c, `resource_groups.${name}`, g, catalog);
    if (!Array.isArray(g.routes) || g.routes.length === 0) {
      throw new ContractError(`resource_groups.${name}.routes must be a non-empty list.`);
    }
    for (const r of g.routes) {
      const where = `resource_groups.${name} route ${r.method} ${r.path}`;
      if (!(HTTP_METHODS as readonly string[]).includes(r.method)) {
        throw new ContractError(`${where}: unknown method '${r.method}'.`);
      }
      if (typeof r.path !== 'string' || !r.path.startsWith('/')) {
        throw new ContractError(`${where}: path must start with '/'.`);
      }
      if (typeof r.auth !== 'boolean' || !Array.isArray(r.scopes)) {
        throw new ContractError(`${where}: auth must be boolean and scopes a list.`);
      }
      if (r.auth && r.scopes.length === 0) throw new ContractError(`${where}: auth route without scopes.`);
      if (!r.auth && r.scopes.length > 0) throw new ContractError(`${where}: public route with scopes.`);
      const key = routeKey(r);
      if (seenRoutes.has(key)) throw new ContractError(`duplicate route '${key}'.`);
      seenRoutes.add(key);
    }
  }
  for (const [name, t] of Object.entries(c.cognito_triggers)) {
    validateFunction(c, `cognito_triggers.${name}`, t, catalog);
  }
  for (const [name, w] of Object.entries(c.workers)) {
    const where = `workers.${name}`;
    validateFunction(c, where, w, catalog);
    const es = w.event_source;
    if (!isObject(es)) throw new ContractError(`${where}.event_source must be an object.`);
    if (es.type === 'sqs') {
      if (!(es.queue in c.queues)) throw new ContractError(`${where}.event_source.queue '${es.queue}' is unknown.`);
      if (!Number.isInteger(es.batch_size) || es.batch_size < 1) {
        throw new ContractError(`${where}.event_source.batch_size must be a positive integer.`);
      }
    } else if (es.type === 'schedule') {
      if (!/^(rate|cron)\(.+\)$/.test(es.expression)) {
        throw new ContractError(`${where}.event_source.expression '${es.expression}' is invalid.`);
      }
    } else {
      throw new ContractError(`${where}.event_source.type '${(es as { type: string }).type}' is unknown.`);
    }
  }
  return c;
}

/** API Gateway route key: `METHOD /path`. */
export function routeKey(r: Pick<RouteSpec, 'method' | 'path'>): string {
  return `${r.method} ${r.path}`;
}

/** Every route in the contract with its group. */
export function allRoutes(c: Contract): Array<RouteSpec & { group: string }> {
  return Object.entries(c.resource_groups).flatMap(([group, g]) => g.routes.map((r) => ({ ...r, group })));
}

function validateFunction(c: Contract, where: string, f: FunctionSpec, catalog: ReadonlySet<string>): void {
  if (typeof f.handler !== 'string' || !/^app\.handlers\.[a-z_]+\.handler$/.test(f.handler)) {
    throw new ContractError(`${where}.handler '${String(f.handler)}' is invalid.`);
  }
  if (!Array.isArray(f.env)) throw new ContractError(`${where}.env must be a list.`);
  const seen = new Set<string>();
  for (const name of f.env) {
    if (!catalog.has(name)) throw new ContractError(`${where}.env '${name}' is not in env_vars.`);
    if (seen.has(name)) throw new ContractError(`${where}.env '${name}' is duplicated.`);
    seen.add(name);
  }
  for (const key of ['memory_mb', 'timeout_seconds'] as const) {
    if (!Number.isInteger(f[key]) || f[key] <= 0) throw new ContractError(`${where}.${key} must be a positive integer.`);
  }
  checkScope(where, 'tables', f.tables, c.tables, TABLE_ACCESS);
  checkScope(where, 'buckets', f.buckets, c.buckets, BUCKET_ACCESS);
  checkScope(where, 'queues', f.queues, c.queues, QUEUE_ACCESS);
  checkScope(where, 'secrets', f.secrets, c.secrets, SECRET_ACCESS);
  checkScope(where, 'parameters', f.parameters, c.parameters, PARAMETER_ACCESS);
  if (!Array.isArray(f.cognito_actions)) throw new ContractError(`${where}.cognito_actions must be a list.`);
  for (const a of f.cognito_actions) {
    if (!/^[A-Z][A-Za-z]+$/.test(a)) throw new ContractError(`${where}.cognito_actions '${a}' is invalid.`);
  }
}

function checkScope(
  where: string,
  kind: string,
  scope: Readonly<Record<string, string>>,
  catalog: Readonly<Record<string, unknown>>,
  levels: readonly string[],
): void {
  if (!isObject(scope)) throw new ContractError(`${where}.${kind} must be an object.`);
  for (const [logical, level] of Object.entries(scope)) {
    if (!(logical in catalog)) throw new ContractError(`${where}.${kind}.${logical} is not in the ${kind} catalog.`);
    if (!levels.includes(level)) throw new ContractError(`${where}.${kind}.${logical} has unknown access '${level}'.`);
  }
}

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}
